require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AcademicTypesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # AcademicType. As you add validations to AcademicType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AcademicTypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all academic_types as @academic_types" do
      academic_type = AcademicType.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:academic_types)).to eq([academic_type])
    end
  end

  describe "GET show" do
    it "assigns the requested academic_type as @academic_type" do
      academic_type = AcademicType.create! valid_attributes
      get :show, {:id => academic_type.to_param}, valid_session
      expect(assigns(:academic_type)).to eq(academic_type)
    end
  end

  describe "GET new" do
    it "assigns a new academic_type as @academic_type" do
      get :new, {}, valid_session
      expect(assigns(:academic_type)).to be_a_new(AcademicType)
    end
  end

  describe "GET edit" do
    it "assigns the requested academic_type as @academic_type" do
      academic_type = AcademicType.create! valid_attributes
      get :edit, {:id => academic_type.to_param}, valid_session
      expect(assigns(:academic_type)).to eq(academic_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AcademicType" do
        expect {
          post :create, {:academic_type => valid_attributes}, valid_session
        }.to change(AcademicType, :count).by(1)
      end

      it "assigns a newly created academic_type as @academic_type" do
        post :create, {:academic_type => valid_attributes}, valid_session
        expect(assigns(:academic_type)).to be_a(AcademicType)
        expect(assigns(:academic_type)).to be_persisted
      end

      it "redirects to the created academic_type" do
        post :create, {:academic_type => valid_attributes}, valid_session
        expect(response).to redirect_to(AcademicType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved academic_type as @academic_type" do
        post :create, {:academic_type => invalid_attributes}, valid_session
        expect(assigns(:academic_type)).to be_a_new(AcademicType)
      end

      it "re-renders the 'new' template" do
        post :create, {:academic_type => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested academic_type" do
        academic_type = AcademicType.create! valid_attributes
        put :update, {:id => academic_type.to_param, :academic_type => new_attributes}, valid_session
        academic_type.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested academic_type as @academic_type" do
        academic_type = AcademicType.create! valid_attributes
        put :update, {:id => academic_type.to_param, :academic_type => valid_attributes}, valid_session
        expect(assigns(:academic_type)).to eq(academic_type)
      end

      it "redirects to the academic_type" do
        academic_type = AcademicType.create! valid_attributes
        put :update, {:id => academic_type.to_param, :academic_type => valid_attributes}, valid_session
        expect(response).to redirect_to(academic_type)
      end
    end

    describe "with invalid params" do
      it "assigns the academic_type as @academic_type" do
        academic_type = AcademicType.create! valid_attributes
        put :update, {:id => academic_type.to_param, :academic_type => invalid_attributes}, valid_session
        expect(assigns(:academic_type)).to eq(academic_type)
      end

      it "re-renders the 'edit' template" do
        academic_type = AcademicType.create! valid_attributes
        put :update, {:id => academic_type.to_param, :academic_type => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested academic_type" do
      academic_type = AcademicType.create! valid_attributes
      expect {
        delete :destroy, {:id => academic_type.to_param}, valid_session
      }.to change(AcademicType, :count).by(-1)
    end

    it "redirects to the academic_types list" do
      academic_type = AcademicType.create! valid_attributes
      delete :destroy, {:id => academic_type.to_param}, valid_session
      expect(response).to redirect_to(academic_types_url)
    end
  end

end
