require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CampusTypesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # CampusType. As you add validations to CampusType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CampusTypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all campus_types as @campus_types" do
      campus_type = CampusType.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:campus_types)).to eq([campus_type])
    end
  end

  describe "GET show" do
    it "assigns the requested campus_type as @campus_type" do
      campus_type = CampusType.create! valid_attributes
      get :show, {:id => campus_type.to_param}, valid_session
      expect(assigns(:campus_type)).to eq(campus_type)
    end
  end

  describe "GET new" do
    it "assigns a new campus_type as @campus_type" do
      get :new, {}, valid_session
      expect(assigns(:campus_type)).to be_a_new(CampusType)
    end
  end

  describe "GET edit" do
    it "assigns the requested campus_type as @campus_type" do
      campus_type = CampusType.create! valid_attributes
      get :edit, {:id => campus_type.to_param}, valid_session
      expect(assigns(:campus_type)).to eq(campus_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CampusType" do
        expect {
          post :create, {:campus_type => valid_attributes}, valid_session
        }.to change(CampusType, :count).by(1)
      end

      it "assigns a newly created campus_type as @campus_type" do
        post :create, {:campus_type => valid_attributes}, valid_session
        expect(assigns(:campus_type)).to be_a(CampusType)
        expect(assigns(:campus_type)).to be_persisted
      end

      it "redirects to the created campus_type" do
        post :create, {:campus_type => valid_attributes}, valid_session
        expect(response).to redirect_to(CampusType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved campus_type as @campus_type" do
        post :create, {:campus_type => invalid_attributes}, valid_session
        expect(assigns(:campus_type)).to be_a_new(CampusType)
      end

      it "re-renders the 'new' template" do
        post :create, {:campus_type => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested campus_type" do
        campus_type = CampusType.create! valid_attributes
        put :update, {:id => campus_type.to_param, :campus_type => new_attributes}, valid_session
        campus_type.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested campus_type as @campus_type" do
        campus_type = CampusType.create! valid_attributes
        put :update, {:id => campus_type.to_param, :campus_type => valid_attributes}, valid_session
        expect(assigns(:campus_type)).to eq(campus_type)
      end

      it "redirects to the campus_type" do
        campus_type = CampusType.create! valid_attributes
        put :update, {:id => campus_type.to_param, :campus_type => valid_attributes}, valid_session
        expect(response).to redirect_to(campus_type)
      end
    end

    describe "with invalid params" do
      it "assigns the campus_type as @campus_type" do
        campus_type = CampusType.create! valid_attributes
        put :update, {:id => campus_type.to_param, :campus_type => invalid_attributes}, valid_session
        expect(assigns(:campus_type)).to eq(campus_type)
      end

      it "re-renders the 'edit' template" do
        campus_type = CampusType.create! valid_attributes
        put :update, {:id => campus_type.to_param, :campus_type => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested campus_type" do
      campus_type = CampusType.create! valid_attributes
      expect {
        delete :destroy, {:id => campus_type.to_param}, valid_session
      }.to change(CampusType, :count).by(-1)
    end

    it "redirects to the campus_types list" do
      campus_type = CampusType.create! valid_attributes
      delete :destroy, {:id => campus_type.to_param}, valid_session
      expect(response).to redirect_to(campus_types_url)
    end
  end

end
